version: '3.8'

services:
  fastapi-app:
    build: .
    command: uvicorn backend.main:app --port 8000 --reload --host 0.0.0.0
    ports:
      - '80:8000'
    volumes:
      - storage:/gopro_storage
    devices:
      - '/dev/bus/usb:/dev/bus/usb'

volumes:
  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pi/storage
